# file: 1_provision.yml
---
# https://www.terraform.io/docs/providers/aws/index.html

- name: Provision AWS Infrastucture using Terraform
  hosts: localhost
  roles:
  - { role: aws.infra, tags: ["tf_create"] }
