# file: roles/wetty/defaults/main.yml
---


openssl_self_signed:
  - name: '{{ domain_name }}'
    domains: ['*.{{ domain_name }}', '{{ domain_name }}']
    country: 'BR'
    state: 'SP'
    city: 'Sao Paulo'
    organization: 'Red Hat'
    unit: 'Pre Sales'
    email: 'rsoares@redhat.com'
    days: 3650

  
key_path:   "home/{{ system_user }}/.wetty/privkey.pem"
cert_path:  "home/{{ system_user }}/.wetty/cert.pem"
wetty_port:  8888
wetty_user: "ec2-user" # "cockpit"