---
# tasks file for common_packages
- name: Install common packges
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Install Openshift clients for RHEL
  yum:
    name: "{{ rhel_oc_client }}"
    state: present
  when: ansible_distribution == 'RedHat'

- name: Install Origin repo for CentOS
  yum:
    name: "{{ centos_origin_repo }}"
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install Origin clients for CentOS
  yum:
    name: "{{ centos_oc_client }}"
    state: present
  when: ansible_distribution == 'CentOS'